  var slide = {};
  slide.data = [
    {
      'name':'家用电器',
      'title':[
        {
          'name':'家电馆',
          'src' :'#'
        },
        {
          'name':'乡镇专卖店',
          'src' :'#'
        },
        {
          'name':'家电服务',
          'src' :'#'
        },
        {
          'name':'家电企业购',
          'src' :'#'
        },
        {
          'name':'商用电器',
          'src' :'#'
        }
      ],
      'details':[
        {
          'detail_name':'电视',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'空调',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'冰箱',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'洗衣机',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        }

      ],
      'adimg':[
        {
          'brand':'美的',
          'src':'#',
          'sources':'./image/meide.jpg'
        },
        {
          'brand':'海尔',
          'src':'#',
          'sources':'./image/haier.jpg'
        },
        {
          'brand':'格力',
          'src':'#',
          'sources':'./image/gree.jpg'
        },
        {
          'brand':'海信',
          'src':'#',
          'sources':'./image/haixin.jpg'
        },
        {
          'brand':'华帝',
          'src':'#',
          'sources':'./image/huadi.jpg'
        },
        {
          'brand':'苏泊尔',
          'src':'#',
          'sources':'./image/suboer.jpg'
        },
        {
          'brand':'康佳',
          'src':'#',
          'sources':'./image/kangjia.jpg'
        },
        {
          'brand':'三菱',
          'src':'#',
          'sources':'./image/sanling.jpg'
        }

      ],
      'sale_banner':[
        {
          'img':'./image/banner1.jpg',
          'src':'#'
        },
        {
          'img':'./image/banner2.jpg',
          'src':'#'
        }
      ]
    },
    {
      'name':'手机/运营商/数码',
      'title':[
        {
          'name':'家电馆',
          'src' :'#'
        },
        {
          'name':'乡镇专卖店',
          'src' :'#'
        },
        {
          'name':'家电服务',
          'src' :'#'
        },
        {
          'name':'家电企业购',
          'src' :'#'
        },
        {
          'name':'商用电器',
          'src' :'#'
        }
      ],
      'details':[
        {
          'detail_name':'电视',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'空调',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'冰箱',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'洗衣机',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        }

      ],
      'adimg':[
        {
          'brand':'美的',
          'src':'#',
          'sources':'./image/meide.jpg'
        },
        {
          'brand':'海尔',
          'src':'#',
          'sources':'./image/haier.jpg'
        },
        {
          'brand':'格力',
          'src':'#',
          'sources':'./image/gree.jpg'
        },
        {
          'brand':'海信',
          'src':'#',
          'sources':'./image/haixin.jpg'
        },
        {
          'brand':'华帝',
          'src':'#',
          'sources':'./image/huadi.jpg'
        },
        {
          'brand':'苏泊尔',
          'src':'#',
          'sources':'./image/suboer.jpg'
        },
        {
          'brand':'康佳',
          'src':'#',
          'sources':'./image/kangjia.jpg'
        },
        {
          'brand':'三菱',
          'src':'#',
          'sources':'./image/sanling.jpg'
        }

      ],
      'sale_banner':[
        {
          'img':'./image/banner1.jpg',
          'src':'#'
        },
        {
          'img':'./image/banner2.jpg',
          'src':'#'
        }
      ]
    },
    {
      'name':'电脑/办公',
      'title':[
        {
          'name':'家电馆',
          'src' :'#'
        },
        {
          'name':'乡镇专卖店',
          'src' :'#'
        },
        {
          'name':'家电服务',
          'src' :'#'
        },
        {
          'name':'家电企业购',
          'src' :'#'
        },
        {
          'name':'商用电器',
          'src' :'#'
        }
      ],
      'details':[
        {
          'detail_name':'电视',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'空调',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'冰箱',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'洗衣机',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        }

      ],
      'adimg':[
        {
          'brand':'美的',
          'src':'#',
          'sources':'./image/meide.jpg'
        },
        {
          'brand':'海尔',
          'src':'#',
          'sources':'./image/haier.jpg'
        },
        {
          'brand':'格力',
          'src':'#',
          'sources':'./image/gree.jpg'
        },
        {
          'brand':'海信',
          'src':'#',
          'sources':'./image/haixin.jpg'
        },
        {
          'brand':'华帝',
          'src':'#',
          'sources':'./image/huadi.jpg'
        },
        {
          'brand':'苏泊尔',
          'src':'#',
          'sources':'./image/suboer.jpg'
        },
        {
          'brand':'康佳',
          'src':'#',
          'sources':'./image/kangjia.jpg'
        },
        {
          'brand':'三菱',
          'src':'#',
          'sources':'./image/sanling.jpg'
        }

      ],
      'sale_banner':[
        {
          'img':'./image/banner1.jpg',
          'src':'#'
        },
        {
          'img':'./image/banner2.jpg',
          'src':'#'
        }
      ]
    },
    {
      'name':'家居/家具/家装/厨房',
      'title':[
        {
          'name':'家电馆',
          'src' :'#'
        },
        {
          'name':'乡镇专卖店',
          'src' :'#'
        },
        {
          'name':'家电服务',
          'src' :'#'
        },
        {
          'name':'家电企业购',
          'src' :'#'
        },
        {
          'name':'商用电器',
          'src' :'#'
        }
      ],
      'details':[
        {
          'detail_name':'电视',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'空调',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'冰箱',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'洗衣机',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        }

      ],
      'adimg':[
        {
          'brand':'美的',
          'src':'#',
          'sources':'./image/meide.jpg'
        },
        {
          'brand':'海尔',
          'src':'#',
          'sources':'./image/haier.jpg'
        },
        {
          'brand':'格力',
          'src':'#',
          'sources':'./image/gree.jpg'
        },
        {
          'brand':'海信',
          'src':'#',
          'sources':'./image/haixin.jpg'
        },
        {
          'brand':'华帝',
          'src':'#',
          'sources':'./image/huadi.jpg'
        },
        {
          'brand':'苏泊尔',
          'src':'#',
          'sources':'./image/suboer.jpg'
        },
        {
          'brand':'康佳',
          'src':'#',
          'sources':'./image/kangjia.jpg'
        },
        {
          'brand':'三菱',
          'src':'#',
          'sources':'./image/sanling.jpg'
        }

      ],
      'sale_banner':[
        {
          'img':'./image/banner1.jpg',
          'src':'#'
        },
        {
          'img':'./image/banner2.jpg',
          'src':'#'
        }
      ]
    },
    {
      'name':'男装/女装/童装/内衣',
      'title':[
        {
          'name':'家电馆',
          'src' :'#'
        },
        {
          'name':'乡镇专卖店',
          'src' :'#'
        },
        {
          'name':'家电服务',
          'src' :'#'
        },
        {
          'name':'家电企业购',
          'src' :'#'
        },
        {
          'name':'商用电器',
          'src' :'#'
        }
      ],
      'details':[
        {
          'detail_name':'电视',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'空调',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'冰箱',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'洗衣机',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        }

      ],
      'adimg':[
        {
          'brand':'美的',
          'src':'#',
          'sources':'./image/meide.jpg'
        },
        {
          'brand':'海尔',
          'src':'#',
          'sources':'./image/haier.jpg'
        },
        {
          'brand':'格力',
          'src':'#',
          'sources':'./image/gree.jpg'
        },
        {
          'brand':'海信',
          'src':'#',
          'sources':'./image/haixin.jpg'
        },
        {
          'brand':'华帝',
          'src':'#',
          'sources':'./image/huadi.jpg'
        },
        {
          'brand':'苏泊尔',
          'src':'#',
          'sources':'./image/suboer.jpg'
        },
        {
          'brand':'康佳',
          'src':'#',
          'sources':'./image/kangjia.jpg'
        },
        {
          'brand':'三菱',
          'src':'#',
          'sources':'./image/sanling.jpg'
        }

      ],
      'sale_banner':[
        {
          'img':'./image/banner1.jpg',
          'src':'#'
        },
        {
          'img':'./image/banner2.jpg',
          'src':'#'
        }
      ]
    },
    {
      'name':'美妆/个护清洁/宠物',
      'title':[
        {
          'name':'家电馆',
          'src' :'#'
        },
        {
          'name':'乡镇专卖店',
          'src' :'#'
        },
        {
          'name':'家电服务',
          'src' :'#'
        },
        {
          'name':'家电企业购',
          'src' :'#'
        },
        {
          'name':'商用电器',
          'src' :'#'
        }
      ],
      'details':[
        {
          'detail_name':'电视',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'空调',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'冰箱',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'洗衣机',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        }

      ],
      'adimg':[
        {
          'brand':'美的',
          'src':'#',
          'sources':'./image/meide.jpg'
        },
        {
          'brand':'海尔',
          'src':'#',
          'sources':'./image/haier.jpg'
        },
        {
          'brand':'格力',
          'src':'#',
          'sources':'./image/gree.jpg'
        },
        {
          'brand':'海信',
          'src':'#',
          'sources':'./image/haixin.jpg'
        },
        {
          'brand':'华帝',
          'src':'#',
          'sources':'./image/huadi.jpg'
        },
        {
          'brand':'苏泊尔',
          'src':'#',
          'sources':'./image/suboer.jpg'
        },
        {
          'brand':'康佳',
          'src':'#',
          'sources':'./image/kangjia.jpg'
        },
        {
          'brand':'三菱',
          'src':'#',
          'sources':'./image/sanling.jpg'
        }

      ],
      'sale_banner':[
        {
          'img':'./image/banner1.jpg',
          'src':'#'
        },
        {
          'img':'./image/banner2.jpg',
          'src':'#'
        }
      ]
    },
    {
      'name':'女鞋/箱包/钟表/珠宝',
      'title':[
        {
          'name':'家电馆',
          'src' :'#'
        },
        {
          'name':'乡镇专卖店',
          'src' :'#'
        },
        {
          'name':'家电服务',
          'src' :'#'
        },
        {
          'name':'家电企业购',
          'src' :'#'
        },
        {
          'name':'商用电器',
          'src' :'#'
        }
      ],
      'details':[
        {
          'detail_name':'电视',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'空调',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'冰箱',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'洗衣机',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        }

      ],
      'adimg':[
        {
          'brand':'美的',
          'src':'#',
          'sources':'./image/meide.jpg'
        },
        {
          'brand':'海尔',
          'src':'#',
          'sources':'./image/haier.jpg'
        },
        {
          'brand':'格力',
          'src':'#',
          'sources':'./image/gree.jpg'
        },
        {
          'brand':'海信',
          'src':'#',
          'sources':'./image/haixin.jpg'
        },
        {
          'brand':'华帝',
          'src':'#',
          'sources':'./image/huadi.jpg'
        },
        {
          'brand':'苏泊尔',
          'src':'#',
          'sources':'./image/suboer.jpg'
        },
        {
          'brand':'康佳',
          'src':'#',
          'sources':'./image/kangjia.jpg'
        },
        {
          'brand':'三菱',
          'src':'#',
          'sources':'./image/sanling.jpg'
        }

      ],
      'sale_banner':[
        {
          'img':'./image/banner1.jpg',
          'src':'#'
        },
        {
          'img':'./image/banner2.jpg',
          'src':'#'
        }
      ]
    },
    {
      'name':'男鞋/运动/户外',
      'title':[
        {
          'name':'家电馆',
          'src' :'#'
        },
        {
          'name':'乡镇专卖店',
          'src' :'#'
        },
        {
          'name':'家电服务',
          'src' :'#'
        },
        {
          'name':'家电企业购',
          'src' :'#'
        },
        {
          'name':'商用电器',
          'src' :'#'
        }
      ],
      'details':[
        {
          'detail_name':'电视',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'空调',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'冰箱',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'洗衣机',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        }

      ],
      'adimg':[
        {
          'brand':'美的',
          'src':'#',
          'sources':'./image/meide.jpg'
        },
        {
          'brand':'海尔',
          'src':'#',
          'sources':'./image/haier.jpg'
        },
        {
          'brand':'格力',
          'src':'#',
          'sources':'./image/gree.jpg'
        },
        {
          'brand':'海信',
          'src':'#',
          'sources':'./image/haixin.jpg'
        },
        {
          'brand':'华帝',
          'src':'#',
          'sources':'./image/huadi.jpg'
        },
        {
          'brand':'苏泊尔',
          'src':'#',
          'sources':'./image/suboer.jpg'
        },
        {
          'brand':'康佳',
          'src':'#',
          'sources':'./image/kangjia.jpg'
        },
        {
          'brand':'三菱',
          'src':'#',
          'sources':'./image/sanling.jpg'
        }

      ],
      'sale_banner':[
        {
          'img':'./image/banner1.jpg',
          'src':'#'
        },
        {
          'img':'./image/banner2.jpg',
          'src':'#'
        }
      ]
    },
    {
      'name':'房产/汽车/汽车用品',
      'title':[
        {
          'name':'家电馆',
          'src' :'#'
        },
        {
          'name':'乡镇专卖店',
          'src' :'#'
        },
        {
          'name':'家电服务',
          'src' :'#'
        },
        {
          'name':'家电企业购',
          'src' :'#'
        },
        {
          'name':'商用电器',
          'src' :'#'
        }
      ],
      'details':[
        {
          'detail_name':'电视',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'空调',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'冰箱',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'洗衣机',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        }

      ],
      'adimg':[
        {
          'brand':'美的',
          'src':'#',
          'sources':'./image/meide.jpg'
        },
        {
          'brand':'海尔',
          'src':'#',
          'sources':'./image/haier.jpg'
        },
        {
          'brand':'格力',
          'src':'#',
          'sources':'./image/gree.jpg'
        },
        {
          'brand':'海信',
          'src':'#',
          'sources':'./image/haixin.jpg'
        },
        {
          'brand':'华帝',
          'src':'#',
          'sources':'./image/huadi.jpg'
        },
        {
          'brand':'苏泊尔',
          'src':'#',
          'sources':'./image/suboer.jpg'
        },
        {
          'brand':'康佳',
          'src':'#',
          'sources':'./image/kangjia.jpg'
        },
        {
          'brand':'三菱',
          'src':'#',
          'sources':'./image/sanling.jpg'
        }

      ],
      'sale_banner':[
        {
          'img':'./image/banner1.jpg',
          'src':'#'
        },
        {
          'img':'./image/banner2.jpg',
          'src':'#'
        }
      ]
    },
    {
      'name':'母婴/玩具乐器',
      'title':[
        {
          'name':'家电馆',
          'src' :'#'
        },
        {
          'name':'乡镇专卖店',
          'src' :'#'
        },
        {
          'name':'家电服务',
          'src' :'#'
        },
        {
          'name':'家电企业购',
          'src' :'#'
        },
        {
          'name':'商用电器',
          'src' :'#'
        }
      ],
      'details':[
        {
          'detail_name':'电视',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'空调',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'冰箱',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'洗衣机',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        }

      ],
      'adimg':[
        {
          'brand':'美的',
          'src':'#',
          'sources':'./image/meide.jpg'
        },
        {
          'brand':'海尔',
          'src':'#',
          'sources':'./image/haier.jpg'
        },
        {
          'brand':'格力',
          'src':'#',
          'sources':'./image/gree.jpg'
        },
        {
          'brand':'海信',
          'src':'#',
          'sources':'./image/haixin.jpg'
        },
        {
          'brand':'华帝',
          'src':'#',
          'sources':'./image/huadi.jpg'
        },
        {
          'brand':'苏泊尔',
          'src':'#',
          'sources':'./image/suboer.jpg'
        },
        {
          'brand':'康佳',
          'src':'#',
          'sources':'./image/kangjia.jpg'
        },
        {
          'brand':'三菱',
          'src':'#',
          'sources':'./image/sanling.jpg'
        }

      ],
      'sale_banner':[
        {
          'img':'./image/banner1.jpg',
          'src':'#'
        },
        {
          'img':'./image/banner2.jpg',
          'src':'#'
        }
      ]
    },
    {
      'name':'食品/酒类/生鲜/特产',
      'title':[
        {
          'name':'家电馆',
          'src' :'#'
        },
        {
          'name':'乡镇专卖店',
          'src' :'#'
        },
        {
          'name':'家电服务',
          'src' :'#'
        },
        {
          'name':'家电企业购',
          'src' :'#'
        },
        {
          'name':'商用电器',
          'src' :'#'
        }
      ],
      'details':[
        {
          'detail_name':'电视',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'空调',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'冰箱',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'洗衣机',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        }

      ],
      'adimg':[
        {
          'brand':'美的',
          'src':'#',
          'sources':'./image/meide.jpg'
        },
        {
          'brand':'海尔',
          'src':'#',
          'sources':'./image/haier.jpg'
        },
        {
          'brand':'格力',
          'src':'#',
          'sources':'./image/gree.jpg'
        },
        {
          'brand':'海信',
          'src':'#',
          'sources':'./image/haixin.jpg'
        },
        {
          'brand':'华帝',
          'src':'#',
          'sources':'./image/huadi.jpg'
        },
        {
          'brand':'苏泊尔',
          'src':'#',
          'sources':'./image/suboer.jpg'
        },
        {
          'brand':'康佳',
          'src':'#',
          'sources':'./image/kangjia.jpg'
        },
        {
          'brand':'三菱',
          'src':'#',
          'sources':'./image/sanling.jpg'
        }

      ],
      'sale_banner':[
        {
          'img':'./image/banner1.jpg',
          'src':'#'
        },
        {
          'img':'./image/banner2.jpg',
          'src':'#'
        }
      ]
    },
    {
      'name':'艺术/礼品鲜花/农资绿植',
      'title':[
        {
          'name':'家电馆',
          'src' :'#'
        },
        {
          'name':'乡镇专卖店',
          'src' :'#'
        },
        {
          'name':'家电服务',
          'src' :'#'
        },
        {
          'name':'家电企业购',
          'src' :'#'
        },
        {
          'name':'商用电器',
          'src' :'#'
        }
      ],
      'details':[
        {
          'detail_name':'电视',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'空调',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'冰箱',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'洗衣机',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        }

      ],
      'adimg':[
        {
          'brand':'美的',
          'src':'#',
          'sources':'./image/meide.jpg'
        },
        {
          'brand':'海尔',
          'src':'#',
          'sources':'./image/haier.jpg'
        },
        {
          'brand':'格力',
          'src':'#',
          'sources':'./image/gree.jpg'
        },
        {
          'brand':'海信',
          'src':'#',
          'sources':'./image/haixin.jpg'
        },
        {
          'brand':'华帝',
          'src':'#',
          'sources':'./image/huadi.jpg'
        },
        {
          'brand':'苏泊尔',
          'src':'#',
          'sources':'./image/suboer.jpg'
        },
        {
          'brand':'康佳',
          'src':'#',
          'sources':'./image/kangjia.jpg'
        },
        {
          'brand':'三菱',
          'src':'#',
          'sources':'./image/sanling.jpg'
        }

      ],
      'sale_banner':[
        {
          'img':'./image/banner1.jpg',
          'src':'#'
        },
        {
          'img':'./image/banner2.jpg',
          'src':'#'
        }
      ]
    },
    {
      'name':'医药保健/计生情趣',
      'title':[
        {
          'name':'家电馆',
          'src' :'#'
        },
        {
          'name':'乡镇专卖店',
          'src' :'#'
        },
        {
          'name':'家电服务',
          'src' :'#'
        },
        {
          'name':'家电企业购',
          'src' :'#'
        },
        {
          'name':'商用电器',
          'src' :'#'
        }
      ],
      'details':[
        {
          'detail_name':'电视',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'空调',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'冰箱',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'洗衣机',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        }

      ],
      'adimg':[
        {
          'brand':'美的',
          'src':'#',
          'sources':'./image/meide.jpg'
        },
        {
          'brand':'海尔',
          'src':'#',
          'sources':'./image/haier.jpg'
        },
        {
          'brand':'格力',
          'src':'#',
          'sources':'./image/gree.jpg'
        },
        {
          'brand':'海信',
          'src':'#',
          'sources':'./image/haixin.jpg'
        },
        {
          'brand':'华帝',
          'src':'#',
          'sources':'./image/huadi.jpg'
        },
        {
          'brand':'苏泊尔',
          'src':'#',
          'sources':'./image/suboer.jpg'
        },
        {
          'brand':'康佳',
          'src':'#',
          'sources':'./image/kangjia.jpg'
        },
        {
          'brand':'三菱',
          'src':'#',
          'sources':'./image/sanling.jpg'
        }

      ],
      'sale_banner':[
        {
          'img':'./image/banner1.jpg',
          'src':'#'
        },
        {
          'img':'./image/banner2.jpg',
          'src':'#'
        }
      ]
    },
    {
      'name':'图书/音像/电子书',
      'title':[
        {
          'name':'家电馆',
          'src' :'#'
        },
        {
          'name':'乡镇专卖店',
          'src' :'#'
        },
        {
          'name':'家电服务',
          'src' :'#'
        },
        {
          'name':'家电企业购',
          'src' :'#'
        },
        {
          'name':'商用电器',
          'src' :'#'
        }
      ],
      'details':[
        {
          'detail_name':'电视',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'空调',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'冰箱',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'洗衣机',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        }

      ],
      'adimg':[
        {
          'brand':'美的',
          'src':'#',
          'sources':'./image/meide.jpg'
        },
        {
          'brand':'海尔',
          'src':'#',
          'sources':'./image/haier.jpg'
        },
        {
          'brand':'格力',
          'src':'#',
          'sources':'./image/gree.jpg'
        },
        {
          'brand':'海信',
          'src':'#',
          'sources':'./image/haixin.jpg'
        },
        {
          'brand':'华帝',
          'src':'#',
          'sources':'./image/huadi.jpg'
        },
        {
          'brand':'苏泊尔',
          'src':'#',
          'sources':'./image/suboer.jpg'
        },
        {
          'brand':'康佳',
          'src':'#',
          'sources':'./image/kangjia.jpg'
        },
        {
          'brand':'三菱',
          'src':'#',
          'sources':'./image/sanling.jpg'
        }

      ],
      'sale_banner':[
        {
          'img':'./image/banner1.jpg',
          'src':'#'
        },
        {
          'img':'./image/banner2.jpg',
          'src':'#'
        }
      ]
    },
    {
      'name':'机票/酒店/旅游/生活',
      'title':[
        {
          'name':'家电馆',
          'src' :'#'
        },
        {
          'name':'乡镇专卖店',
          'src' :'#'
        },
        {
          'name':'家电服务',
          'src' :'#'
        },
        {
          'name':'家电企业购',
          'src' :'#'
        },
        {
          'name':'商用电器',
          'src' :'#'
        }
      ],
      'details':[
        {
          'detail_name':'电视',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'空调',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'冰箱',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        },
        {
          'detail_name':'洗衣机',
          'src' : '#',
          'items':[
            {
            'item_name':'曲面电视',
            'src':'#'
            },
            {
            'item_name':'超薄电视',
            'src':'#'
            },
            {
            'item_name':'OLED电视',
            'src':'#'
            },
            {
            'item_name':'4K超清电视',
            'src':'#'
            },
            {
            'item_name':'55英寸',
            'src':'#'
            },
          ]
        }

      ],
      'adimg':[
        {
          'brand':'美的',
          'src':'#',
          'sources':'./image/meide.jpg'
        },
        {
          'brand':'海尔',
          'src':'#',
          'sources':'./image/haier.jpg'
        },
        {
          'brand':'格力',
          'src':'#',
          'sources':'./image/gree.jpg'
        },
        {
          'brand':'海信',
          'src':'#',
          'sources':'./image/haixin.jpg'
        },
        {
          'brand':'华帝',
          'src':'#',
          'sources':'./image/huadi.jpg'
        },
        {
          'brand':'苏泊尔',
          'src':'#',
          'sources':'./image/suboer.jpg'
        },
        {
          'brand':'康佳',
          'src':'#',
          'sources':'./image/kangjia.jpg'
        },
        {
          'brand':'三菱',
          'src':'#',
          'sources':'./image/sanling.jpg'
        }

      ],
      'sale_banner':[
        {
          'img':'./image/banner1.jpg',
          'src':'#'
        },
        {
          'img':'./image/banner2.jpg',
          'src':'#'
        }
      ]
    }
]
